# Generated by Django 5.0.6 on 2024-05-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationApp', '0003_user_details_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='donation_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raised', models.IntegerField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='signup_model',
        ),
    ]
