# Generated by Django 5.0.6 on 2024-05-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationApp', '0004_donation_list_delete_signup_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation_list',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
