# Generated by Django 5.0.6 on 2024-05-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationApp', '0005_donation_list_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='donation_amount',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
