# Generated by Django 5.0.6 on 2024-05-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationApp', '0006_user_details_donation_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_list',
            name='raised',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='donation_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
