# Generated by Django 5.0.6 on 2024-05-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationApp', '0009_user_details_donation_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='donation_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('donation_number', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
