# Generated by Django 5.0.6 on 2024-05-16 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donationApp', '0010_donation_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='donation_number',
            new_name='donation_details',
        ),
    ]
