# Generated by Django 5.0.6 on 2024-05-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationApp', '0011_rename_donation_number_donation_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation_details',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
